### ISSUE TITLE
Tag Issue

### ISSUE THREAD

**Issue by ModernGamingWorld** [JDKDigital/productivetrees#1]
I could be wrong, not sure if they removed it in 1.20.1, but shouldn't your rubber be tagged under the forge rubber tag? This would allow it to be used by other mods that use the rubber tag for their recipes and would include yours if tagged right.

coffee_bean is not included in the forge:crops/coffee_beans tag
cinnamon is not included in the forge:crops/cinnamon tag
Nutmeg is not included in the forge:crops/nutmeg tag

I am sure there is a ton more missing tags, I know this mod is still new, but without tag support it wont work well with other mods that use tags for recipes

**Comment by JaisDK** [comment]
https://github.com/JDKDigital/productivetrees/blob/dev-1.20.1/src/generated/resources/data/forge/tags/items/rubber.json
https://github.com/JDKDigital/productivetrees/blob/dev-1.20.1/src/generated/resources/data/forge/tags/items/cinnamon.json

nutmeg and coffee_beans need to be added still, for coffee_beans I guess I should use the roasted version
