### ISSUE TITLE
[Suggestion] Add Tags to Fence Gates

### ISSUE THREAD

**Issue by TheBedrockMaster** [JDKDigital/productivetrees#10]
Fence Gates are missing tags, they should have these tags:

minecraft:fence_gates
forge:fence_gates
forge:fence_gates/wooden

**Comment by JaisDK** [comment]
`minecraft:wooden_fence_gates` doesn't seem to exist and `forge:fence_gates` includes `forge:fence_gates/wooden` so I would just need to add them to the latter :thumbsup:

**Comment by TheBedrockMaster** [comment]
Just minecraft:fence_gates, my mistake.

> `minecraft:wooden_fence_gates` doesn't seem to exist and `forge:fence_gates` includes `forge:fence_gates/wooden` so I would just need to add them to the latter 👍

**Comment by TheBedrockMaster** [comment]
Could this come to 1.20.1 so they can have EMC in 9sky?
