### ISSUE TITLE
Fast leaves are rendered with a white background instead of a black background

### ISSUE THREAD

**Issue by Lolothepro** [JDKDigital/productivetrees#13]
Modded leaves:

![2024-07-19_12 32 16](https://github.com/user-attachments/assets/bdc65e09-80d2-4a8b-bd8c-050413c65655)

Vanilla leaves:

![2024-07-19_12 33 00](https://github.com/user-attachments/assets/b98d5368-84de-4316-9a30-bf7f2b879b29)

**Comment by JaisDK** [comment]
it's probably because I use a different render type in order to support translucent leaves
it's not something I'm gonna change
