### ISSUE TITLE
[1.21-Neo] Very rare modloading error crash when booting server.

### ISSUE THREAD

**Issue by Gbergz** [JDKDigital/productivetrees#14]
The modloading error is very rare, but it can happen.

Crash-report: https://gist.githubusercontent.com/Gbergz/d349ddc128413fdb88891d67f129b319/raw/c1091bd508201f323a50ab9fad6a73b494b389d1/gistfile1.txt

MC: 1.21
NeoForge: 21.0.97
Productive Trees: 0.3.4

**Comment by JaisDK** [comment]
Do you have a log from this?

**Comment by Gbergz** [comment]
Maybe. I'll have to dig into the logs folder

**Comment by Gbergz** [comment]
Definitely forgot about this, but here's the log:
https://gist.githubusercontent.com/Gbergz/7cfe50651d6dd746498ad8dd8633bced/raw/6ad276a8941dddae0ce79286bfc7ed9f9018f2b5/gistfile1.txt

**Comment by JaisDK** [comment]
I had put a fix for this in the last version, but a side effect is that sign textures are gone so I have to revert the change. I can try to put in some guards against crashing there.
