### ISSUE TITLE
Saw Mill not registered as work station for its recipes

### ISSUE THREAD

**Issue by rlnt** [JDKDigital/productivetrees#15]
The Saw Mill block is not registered as work station for Saw Mill recipes. You can only access sawing recipes by looking at the recipes for Saw Dust but you can't access them by viewing the usages for the Saw Mill because of that.

It should be listed in the category like this:
![](https://i.imgur.com/x6ceO43.png)

However, the page doesn't have any work station associated:
![](https://i.imgur.com/jpnFDHg.png)

**Comment by JaisDK** [comment]
I'm guessing this is EMI?

**Comment by rlnt** [comment]
Yup, sorry. Forgot to add that.
