### ISSUE TITLE
Using upgrades on Pollen Sifter crashes the game

### ISSUE THREAD

**Issue by NielsPilgaard** [JDKDigital/productivetrees#17]
Relay of https://github.com/EnigmaticaModpacks/Enigmatica10/issues/71

productivetrees-1.21.0-0.4.1
[Crash report](https://gist.github.com/rybacki-t/6c668424a62080419c96c3a2ce2852e0)

**Comment by JaisDK** [comment]
Putting up a new version now, it needed one more mod loaded check.
