### ISSUE TITLE
[Feature Request] Mekanism Sawmill compat

### ISSUE THREAD

**Issue by Saereth** [JDKDigital/productivetrees#19]
Would be nice if the mod could have compatibility for the mekanism sawmill as well, thanks!

**Comment by Saereth** [comment]
Nevermind, I just made an addon for it :p 
https://github.com/Saereth/productivetrees-mekanism-compatibility

**Comment by JaisDK** [comment]
cool, but I'm still gonna add it in the mod when I work on it again

**Comment by Saereth** [comment]
no worries, if you wanna ping me once you do I'll update the addon description and let everyone know its deprecated at that point :)

**Comment by JaisDK** [comment]
This is now in the mod

**Comment by Saereth** [comment]
ok, added a notice onto the mod page to tell people they wont need it anymore after the version where compat was added.
