### ISSUE TITLE
Dogwood and Wild Cherry have the same recipe

### ISSUE THREAD

**Issue by SunDrop73** [JDKDigital/productivetrees#20]
Dogwood and wild cherry both have the same recipe. Silver Lime and Cherry
Playing on ATM 10 0.52, Tree version 0.50

**Comment by JaisDK** [comment]
is that a problem?

**Comment by SunDrop73** [comment]
yes, trying to make a wild cherry sapling and it always makes the dogwood sapling

**Comment by JaisDK** [comment]
how many times did you try and which pollen are you using on what leaf?

**Comment by SunDrop73** [comment]
12ish times so far and i have tried it both ways. cherry pollen on to silver lime leaves and silver polen onto cherry leaves

**Comment by JaisDK** [comment]
That combination makes 3 different saplings and I'm getting a decent distribution so just keep trying
![image](https://github.com/user-attachments/assets/b08e3541-1485-40b6-bccd-c49793c1741b)
