### ISSUE TITLE
More Missing Sapling Recipes

### ISSUE THREAD

**Issue by Motytheultimate** [JDKDigital/productivetrees#21]
I found the textures and the implementation for the following saplings.
They are however missing recipes

Pink Ipe
purple ipe
Red Crepe Myrtle Sapling
Moonlight Magic Crepe Myrtle Sapling
Tuscarora Crepe Myrtle Sapling

**Comment by JaisDK** [comment]
they are not missing, you keep growing the ipe and myrtle you can get from breeding and there's a chance to grow into the other ones

**Comment by JaisDK** [comment]
ipe -> white ipe -> pink ipe -> purple ipe

purple crepe myrtle -> red -> tuscarora -> moonlight

**Comment by Motytheultimate** [comment]
Oh I see ill try that tomorrow, i just couldnt find any information about them online

**Comment by Motytheultimate** [comment]
Confirmed its working as its supposed to

**Comment by BinLox** [comment]
Are we supposed to just keep planting, bone mealing, chopping down, and repeat ad infinitum until we get the right one, or?

**Comment by JaisDK** [comment]
yes, as stated
