### ISSUE TITLE
Another KubeJS Error

### ISSUE THREAD

**Issue by NielsPilgaard** [JDKDigital/productivetrees#22]
Heya \o

I got this error while running Productive Trees, without Productive Bees, on a server. It does not happen in singleplayer.

`[22:35:20] [ERROR] ! Skipping recipe productivetrees:allergy_bee, error parsing conditions: Unknown registry key in ResourceKey[minecraft:root / neoforge:condition_codecs]: productivebees:bee_exists`

`productivetrees-1.21.1-0.5.4`

**Comment by JaisDK** [comment]
why would it do that now and not before? it's a NeoForge issue which I've raised with them before, when you use recipe conditions that another mod defines then it will still try to parse them even though the mod_loaded condition is false.

there is an idiotic way around it which I'll have to look into
