### ISSUE TITLE
crash with 0.6.0

### ISSUE THREAD

**Issue by VaporeonScripts** [JDKDigital/productivetrees#24]
https://mclo.gs/2OAvBeV
neoforge 1.21.1 .80

**Comment by JaisDK** [comment]
interesting, thanks for the report

if you don't want to wait until I fix it you can add the mod Tree Tap, that should stop the crash

**Comment by VaporeonScripts** [comment]
ill wait for now

**Comment by JaisDK** [comment]
Your wait is finally over! (I hope)

thank you for shopping with lobstermods
