### ISSUE TITLE
Generated JSONs in /config/productivetrees/generated/data/productivetrees

### ISSUE THREAD

**Issue by NielsPilgaard** [JDKDigital/productivetrees#25]
Hi 👋 

After updating Productive Trees and starting Minecraft, I suddenly have 23000+ new files in my config folder. Did you by chance accidentally point your datagen into the wrong folder? :P

**Comment by JaisDK** [comment]
That is on purpose, I moved everything to dynamically generated resources to allow for some other changes later.

**Comment by NielsPilgaard** [comment]
I see. May I ask what the benefit of having them in configs instead of your jar file is? 😊

**Comment by JaisDK** [comment]
There are two things it will open up for. One is to be able to add your own trees with just a single json file and second will be to run the mod in a minimal mode where all the additional wood blocks like stairs, buttons etc. are not registered effectively cutting the number of blockstates by more than half (from 124658 to 57104). The idea is that Framed Blocks can pick up the slack.

Is it causing issues that the resources are in the config folder?

**Comment by NielsPilgaard** [comment]
Ah okay, makes sense, thanks for explaining 😊

It's going to increase modpack build time quite a bit, due to all the extra files that need to be zipped.

**Comment by JaisDK** [comment]
You don’t need to include them in your build, they will be generated on the players side
