### ISSUE TITLE
Sapling Dupe

### ISSUE THREAD

**Issue by FoxSketchez** [JDKDigital/productivetrees#4]
Placing a Productive trees sapling in a flowerpot (minecraft)
and then right clicking it (as to take it out) will dupe the sapling.
seems to effect all the Productive trees sapling

Mod Version: 1.20.1 - 0.1.4
Mod Pack: ATM 9

**Comment by JaisDK** [comment]
Thanks for reporting, didn't even know you could get the sapling out without breaking the pot.
