### ISSUE TITLE
Jade/Waila support for advanced beehive contents (feature request)

### ISSUE THREAD

**Issue by biochemie** [JDKDigital/productivetrees#6]
Just curious if there are plans to add Jade support for viewing hive contents similar to that in the Productive Bees mod. Would help add to the seamlessness in pairing the two mods together!

**Comment by JaisDK** [comment]
The hives from this mod is made with the code in pbees so they should be identical. Are they not?

**Comment by biochemie** [comment]
There's some compat stuff as well in Productive Bees, wherein it appears the Waila integration is.
https://github.com/JDKDigital/productive-bees/blob/dev-1.20.0/src/main/java/cy/jdkdigital/productivebees/compat/hwyla/ProductiveBeesWailaPlugin.java

**Comment by JaisDK** [comment]
yes, but does it not work in game? The hives are the same code in the two mods.

**Comment by biochemie** [comment]
No; Jade/Waila don't provide any details about the Productive Trees advanced beehives, unlike the Productive Bees advanced beehives (which will show contents, including bees and their products).

I would presume that the hives themselves don't provide the Jade/Wailia information integration. That's what the file in the link appears to provide (the ability for Jade/Wailia to query and obtain the beehive's additional data).

**Comment by biochemie** [comment]
Additional information from Jade's docs also appears to indicate as much. https://jademc.readthedocs.io/en/latest/plugins20/getting-started/#registering

**Comment by JaisDK** [comment]
can you show a screenshot of the difference?

**Comment by biochemie** [comment]
I apparently cannot; I'm not sure what happened between yesterday and today, but it seems to be working the same between the two mods right now upon testing. Boy do I feel embarassed right now for not checking again before posting!

So sorry to have bothered you/opened this! :grimacing:
