### ISSUE TITLE
Missing Saping Recipes

### ISSUE THREAD

**Issue by FoxSketchez** [JDKDigital/productivetrees#7]
Productive Trees is missing the sapling Copper Beech or Jei isn't listing it.
**Update:** Upon further investigation, I've found a few more saplings missing from Jei
They are; Beech, Blackthorn, Ipe, Juniper, Purple Blackthorn, Purple Crepe Myrtle, Red Crepe Myrtle and Tuscarora Crepe Myrtle

Mod Pack: ATM 9
Mod: Productive Trees
Mod Version: 1.20.1 - 0.2.1

**Comment by JaisDK** [comment]
as designed https://github.com/JDKDigital/productivetrees/issues/21
