### ISSUE TITLE
Mod Fails When Loading

### ISSUE THREAD

**Issue by XRealismX** [JDKDigital/productivetrees#8]
So I was creating a modpack for 1.21 on NeoForge, then added the Productive Trees mod, and then it stopped working, so I opened up another instance just with this mod to see if that was the cause, and it ended up being the problem.

lastest.log > https://mclo.gs/5Bms884
Crash Log > https://mclo.gs/4ZeohI6

![image](https://github.com/JDKDigital/productivetrees/assets/13025294/3fd6201a-8c07-4ead-82c4-2136776d5f2d)

**Comment by JaisDK** [comment]
looks like I managed to add a hard dependency on productive bees
