### ISSUE TITLE
Many KubeJS errors when Productive Trees is present

### ISSUE THREAD

**Issue by NielsPilgaard** [JDKDigital/productivetrees#9]
Hi 👋 

I added Productive Trees to Enigmatica 10 in-dev, and suddenly had 481 KubeJS errors:
https://gist.github.com/NielsPilgaard/0734de96c45dffcdc24cfb8494ec2bc8

- productivetrees-1.21.0-0.3.0
- kubejs-2100.7.0-build.63
- neoforge 21.0.52

**Comment by NielsPilgaard** [comment]
The issue still occurs in v0.3.3

**Comment by JaisDK** [comment]
same errors?

**Comment by NielsPilgaard** [comment]
Ah right, no not entirely the same: https://gist.github.com/NielsPilgaard/bb873d82d509e6c200a8cd14d03f8c08

**Comment by JaisDK** [comment]
right, the issue is that I use the wrong condition in the recipe file so it wants productive bees installed
I'll get a new version out soon

**Comment by NielsPilgaard** [comment]
Sounds good, thank you 😊

**Comment by JaisDK** [comment]
it's up

**Comment by NielsPilgaard** [comment]
We're now down to only 1 KubeJS error! 👍 
New logs: https://gist.github.com/NielsPilgaard/94f17ec4948ebbc4788d9c902314bd46

**Comment by JaisDK** [comment]
I don't understand why KJS would complain about that recipe, it works just fine. Do you know why it complains?
https://github.com/JDKDigital/productivetrees/blob/dev-1.21.0/src/main/resources/data/productivetrees/recipe/pollen_sieve.json

**Comment by JaisDK** [comment]
so, that item is not supposed to be there when bees are not installed, that's why the recipe complains

**Comment by JaisDK** [comment]
@NielsPilgaard got anymore errors in the latest?

**Comment by NielsPilgaard** [comment]
Yes 😂 They're persistent!
https://gist.github.com/NielsPilgaard/f59ef3849120909d135e5773df546da0

**Comment by JaisDK** [comment]
Yea that one is because MI has decided to include Parchouli as JIJ which activated the guide book recipe. I have a build teady for it just wanted to check with you that there wasn’t anything else.
